language: rust
rust:
  - stable
  - beta
  - nightly

# Need semi-recent g++ (for jsonnet-sys)
dist: trusty
group: beta

sudo: false

env:
  - RUST_BACKTRACE=1
script:
  - cargo build --verbose
  - cargo test --verbose

notifications:
  email:
    on_success: never
